// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    citizen_nft_minting_sc
    (
        init => init
        upgrade => upgrade
        request_mint_citizen => request_mint_citizen
        claim_citizen => claim_citizen
        request_upgrade_to_soldier => request_upgrade_to_soldier
        claim_soldier => claim_soldier
        upgrade_soldier_with_shield => upgrade_soldier_with_shield
        upgrade_soldier_with_sword => upgrade_soldier_with_sword
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
