// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    issue_token_snow_sc
    (
        init => init
        upgrade => upgrade
        issue_token_snow => issue_token_snow
        issue_token_snow_and_transfer => issue_token_snow_and_transfer
        burn_token => burn_token
        get_account_tokens => get_account_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback! { issue_token_snow_sc }
