[package]
name = "issue-token-snow-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.issue-token-snow-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
default-features = false
